- sgeop/geometry.py
- sgeop/tests/test_geometry.py
This MR:
* starts fine-grained testing in `sgeop`, which will (hopefully) make #7 easier done the line.
* resolves #23
> testing for `geometry.angle_between_two_lines()`

- sgeop/geometry.py
- sgeop/tests/test_geometry.py
This PR:
* chips way some refactoring in `geometry.py`
* DRYs out `geometry.snap_to_targets()` & breaks out some helper funds
* add dedicated granular test for helpers
* xref #20
> chip away some refactors in `geometry.py`

- sgeop/continuity.py
- sgeop/tests/test_continuity.py
This PR:
* provides dedicated minimal tests for `continuity.py`
* beefs up docstrings & type types
* small refactoring for DRYness
* resolves #49
> dedicated minimal tests for `continuity.py`

- sgeop/nodes.py
- sgeop/tests/test_nodes.py
This PR:
* adds dedicated minimal tests for `nodes.weld_edges()`
* xref #21, #20
* adds testing
* adds docstrings and type hints
> dedicated minimal tests -- `nodes.weld_edges()`

- sgeop/geometry.py
- sgeop/nodes.py
- sgeop/tests/test_nodes.py
This PR:
* adds dedicated minimal tests for `nodes.remove_false_nodes()`
* resolves #60 
* xref 
* #21 
* #20
* https://github.com/pysal/momepy/pull/661
* adds testing
* adds docstrings and type hints
> dedicated minimal tests -- `nodes.remove_false_nodes()`

- sgeop/nodes.py
This is a small PR that cleans up the `nodes.fix_topology()` docstring and adds type hints.
> clean up `nodes.fix_topology()` docstring + type hints

- sgeop/tests/conftest.py
- sgeop/tests/test_simplify.py
This MR provides granular testing of network geometries on comparison failure, generally due to slight differences in geometry based on GEOS version. Moreover, known exceptions/edge cases can be added to `conftest.py` for easy debugging and sanity check.
* resolves #77 
* resolves #75 
* supersedes #76 
* the [Windows failure](https://github.com/uscuni/sgeop/actions/runs/11696516451/job/32573750004?pr=78#step:3:529) is some weirdness unrelated to this MR.
> granular geometry testing on failure

- CONTRIBUTING.md
This PR:
* resolves #81
* xref #48
> edge cases section in `CONTRIBUTING.md`

- sgeop/nodes.py
This PR:
* document why #83 is needed
* resolves #83
> add explanation of final `if` in `nodes._status()`

- sgeop/artifacts.py
- sgeop/continuity.py
- sgeop/geometry.py
- sgeop/simplify.py
This PR:
* adds a detailed docstring & typehints for `simplify.network_simplify()`
* makes corrections/updates to several other functions throughout
* xref #20 
* xref #5 
Once we are satisfied with the wording, I will propagate docstrings & typehints in the internal functions in a follow up PR.
> docstring & typehints in `simplify.network_simplify()`, etc.

- .pre-commit-config.yaml
- sgeop/simplify.py
This PR:
* continues docstring/type hint work for `simplify`
* adds docstrings & type hints for `simplify.simplify_loop()`
* adds more explanation to the `simplify.simplify_network()` explanation
* update `ruff` version in `pre-commit`
* xref
* #20 
* #5
> docstring & typehints in simplify.simplify_loop(), etc.

- sgeop/simplify.py
This PR:
* continues docstring/type hint work for `simplify`
* adds docstrings & type hints for `simplify.simplify_singletons()`
* xref
* #20 
* #5
> docstring & typehints in simplify.simplify_singletons(), etc.

- sgeop/artifacts.py
* This PR:
* does doc work + type hints in `artifact.multiple_remaining()`
* add to `artifacts.one_remaining_c()` docstring
* xref: https://github.com/uscuni/sgeop/issues/20
> doc work + type hints in `artifact.multiple_remaining()`, etc.

- sgeop/nodes.py
> adopt CRS inducing nodes – fix CRS warning

- sgeop/artifacts.py
* This PR adds a docstring & type hints to `artifact.one_remaining()`.
* #20
> doc work + type hints in `artifact.one_remaining()`

- sgeop/simplify.py
This PR:
* does doc work + type hints + refactor + comments `simplify.simplify_pairs()`
* better explanation & comments – doc work refactor `simplify.simplify_singletons()`
* some DRYing & breaking out of helper funcs
* xref: 
* https://github.com/uscuni/sgeop/issues/20
* https://github.com/uscuni/sgeop/issues/21
* Questions regarding `non-planar clusters of value 2`
* Q1: [`simplify@L351`](077b92ec5fb342ab222ccf9328c5a33c1bde0b6a28bd285e09ec42a51c04d73eR351)
* Q2: [`simplify@L355`](https://github.com/uscuni/sgeop/pull/116/files#diff-077b92ec5fb342ab222ccf9328c5a33c1bde0b6a28bd285e09ec42a51c04d73eR353)
> doc work + type hints + refactor `simplify.simplify_{singletons, pairs}()`, etc.

- sgeop/artifacts.py
This PR:
* adds docstring + type hints to `artifacts.remove_dangles()`
* adds docstring + type hints to `artifacts.is_dangles()`
* does small internal refactor within `artifacts.is_dangles()`
* xref #20
> doc work + type hints + refactor – `artifacts.py` -- dangles

- sgeop/artifacts.py
This PR:
* adds docs & typehints for `artifacts.py.{ccss_special_case(), filter_connections()}`
* does a very small refactor inside `filter_connections()`
* several typos of "linestring" --> "linestrings"
* xref #20
> docs & typehints - `artifacts.py.{ccss_special_case(), filter_connections()}`

- neatnet/nodes.py
Fixes Wuhan crashing on Apple Silicon. `_shared_node` had two unique values. Calling `mode` fixes that.
> BUG: fix Wuhan crash

- neatnet/artifacts.py
This PR is a small DRY/refactor in `artifacts.nx_gx()`.
> small refactor in `artifacts.nx_gx()`

- .github/workflows/mypy.yml
- .github/workflows/testing.yml
- .pre-commit-config.yaml
- ci/py311_latest.yaml
- ci/py311_oldest.yaml
- ci/py312_latest.yaml
- ci/py313_dev.yaml
- ci/py313_latest.yaml
- codecov.yml
- environment.yml
- pyproject.toml
lint yaml files & add to pre-commit -- #161
> lint yaml files & add to pre-commit -- #161

- .github/release.yml
- .github/workflows/release_to_pypi.yml
- .pre-commit-config.yaml
- neatnet/artifacts.py
> add release action and GH -> PyPI trusted publisher

- .github/workflows/testing.yml
Closes #181 
I am not sure why we had it in the first place, given we have only one job anyway.
> allow CI to fail

- neatnet/tests/conftest.py
- neatnet/tests/test_simplify.py
This PR:
* provides more robust checking of "known" vs. observed neatified resulted
* normalized and sorts all geometries, both known and observed
* when **complete** geometry comparison goes sour:
* compares record by record:
* geometry (already doing)
* topology
* when comparison fails record per edge :
* number of constituent coords (already doing)
* length (already doing)
* number of touching edges
* presorted index location
* report any failures and curate failing selection for easier comparison 
------------------------
resolves #245
> more robust checking of results in testing - geometry & topology
