uscuni/neatnet

ci/py311_sgeop-oldest.yaml, environment.yml, pyproject.toml
=> add pyarrow as a testing req

sgeop/nodes.py, sgeop/simplify.py
=> revert 2 commits - resolve #35

sgeop/nodes.py, sgeop/simplify.py
hopefully better solution for those botched commits from yesterday
=> fixes for uncaught non-planar pair and split function

CONTRIBUTING.md, README.md
This PR:
* resolves #4 
* kicks off #7 – gives a structure, but we can work on ironing out the wording if needed. I welcome input on language, other sections, etc.
=> Create CONTRIBUTING.md -- document procedure

sgeop/simplify.py
=> address #47 -- pandas DeprecationWarning

pyproject.toml, sgeop/tests/test_geometry.py
=> full coverage for `geometry.py` with minimal tests

sgeop/artifacts.py, sgeop/geometry.py
=> update keyword in `voronoi_skeleton()`

sgeop/geometry.py, sgeop/nodes.py, sgeop/tests/test_nodes.py
This PR:
* adds dedicated minimal tests for `nodes.get_components()`
* resolves #56 
* xref #21, #20
* adds testing
* adds docstrings and type hints for:
*  `nodes.get_components()`
* `nodes._status()`
* (updated) `geometry.voronoi_skeleton()`
=> dedicated minimal tests -- `nodes.get_components()`

sgeop/simplify.py
=> `simplify.py` -- swap order of `simplify_clusters()` & `simplify_pairs()`

sgeop/artifacts.py, sgeop/simplify.py
=> swap all `limit_distance` to `clip_limit`

CONTRIBUTING.md
This PR pushed forward with progress on the `CONTRIBUTING.md` document.
* xref: #48 
* based on:
* [`clustergram/CONTRIBUTING.md`](https://github.com/martinfleis/clustergram/blob/main/CONTRIBUTING.md)
* [`contributing-gen`](https://github.com/bttger/contributing-gen)
* This is not meant to be the final product, but a much more developed draft (perhaps near a final product?
* Will need name update following resolution of #64  +++ link updating
* Will need link updating for docs if we do a RTD site -- #5
=> progress on CONTRIBUTING.md

sgeop/artifacts.py
* This PR:
* doc work + type hints in `artifacts.py` [part 1] 
* resolves #99 
* resolves #100 
* resolves #108 
* other comment work
=> doc work + type hints in `artifacts.py` [part 1]

sgeop/artifacts.py
* This PR does doc work + type hints in `artifacts.one_remaining_c()`
* xref: https://github.com/uscuni/sgeop/issues/20
=> doc work + type hints in `artifacts.one_remaining_c()`

sgeop/artifacts.py
This PR:
* resolves #11 
* more explanation in [comment](https://github.com/uscuni/sgeop/issues/11#issuecomment-2510419897)
=> Vectorized explode LineStrings into constituent pairwise segments

sgeop/simplify.py, sgeop/tests/conftest.py
=> flag for global exception raising in debugging

sgeop/simplify.py
This PR:
* adds docs & typehints for `simplify.simplify_clusters()`
* adds & updates some comments
* xref #20
=> docs/typehints/comments – `simplify.simplify_clusters()`

.github/workflows/mypy.yml, .github/workflows/testing.yml, .pre-commit-config.yaml, sgeop/artifacts.py, sgeop/continuity.py, sgeop/geometry.py, sgeop/nodes.py, sgeop/simplify.py, sgeop/tests/conftest.py
This PR:
* resolves #131 
* fixes all typing rough edges currently in the code base
* adds a `mypy` workflow ~~& `pre-commit` hook (willing to remove the hook if we think it's too much)~~
=> `mypy` type checking review, workflow, hook

neatnet/simplify.py
=> add projected CRS meters info – #142

.pre-commit-config.yaml
This PR implements a TOML linter in pre-commit like that over in https://github.com/uscuni/simplification/pull/226.
=> TOML linter in pre-commit

CONTRIBUTING.md
=> fill placeholders in contributing guide

README.md
Just realised that this might be good idea.
=> funding note

neatnet/artifacts.py, neatnet/gaps.py, neatnet/nodes.py, neatnet/simplify.py, neatnet/tests/test_gaps.py, pixi.lock, pyproject.toml
=> code health checkup -- docstring, type-hints, signatures

neatnet/artifacts.py
This makes get_artifacts runtime in Aleppo down to 2.1s from 24.4s.
=> use Graph.apply instead of Series.apply in get_artifacts

neatnet/artifacts.py, neatnet/simplify.py, neatnet/tests/test_simplify.py
Closes #200
Not entirely sure how to ideally tests this without too much hassle. Our existing networks do find thresholds even when simplified.
=> add default artifact_threshold_fallback

neatnet/simplify.py
Update simplify.py - docstring artifact_threshold_fallback
xref: #201
=> Update simplify.py - docstring artifact_threshold_fallback

neatnet/nodes.py, neatnet/simplify.py, pixi.lock
=> PERF: nodes from LineString gdf

neatnet/artifacts.py, neatnet/continuity.py, neatnet/nodes.py, neatnet/simplify.py, neatnet/tests/test_artifacts.py
This PR:
* resolves #211 
* resolves #222 
* starts on #141 
* replaces "road(s)" with "street(s)" in the docstrings and comments
* does not touch variable naming yet, etc.
=> docstring work and input clarifications

neatnet/nodes.py, neatnet/tests/test_nodes.py, neatnet/tests/test_simplify.py
* This is a ~~***preliminary & inefficient***~~ fix for #214
* Works for the small synthetic cases
* ~~Seems to work for the Apalachicola test case~~
* ~~***But*** gets completely bogged down in full scale empirical examples~~
* ***Works for all cases and verified run on the exact Singapore example with buildings in [#214](#214)***
=> include "bowtie" logic with `nodes.get_components()`

neatnet/artifacts.py
=> try/except removal in `artifacts.FaceArtifacts` for `esda` 

neatnet/simplify.py
I ran into a weird cornercase which should not happen but it did :D. This seems to fix it so far. I wasn't able to debug it properly as it was running in parallel and I am not sure in which of my 700 regions it occured :).
=> fix a cornercase in get_solution
